blank_issues_enabled: true
contact_links:
  - name: ❓ Q&A Technical Support Channel
    url: https://aleo.org/discord
    about: For quick questions or technical troubleshooting, please ask them on our dedicated Discord channel.
