name: Dev CI

on:
    push:
        branches: [ "main", "dev" ]
    pull_request:
        branches: [ "main", "dev" ]
    workflow_dispatch:

jobs:
    environment-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - name: install dependencies
              run: |
                pip install networkx[default]
                pip install lark
            - name: test hello.py
              run: python tests/scripts/hello.py
            - name: test dep.py
              run: python tests/scripts/dep.py

    parser-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - name: install dependencies
              run: |
                pip install networkx[default]
                pip install lark
            - name: test parsing.py
              run: PYTHONPATH="./" python ./tests/scripts/parsing.py

    detector-test-divz:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - name: install dependencies
              run: |
                pip install networkx[default]
                pip install lark
            - name: test parsing.py
              run: PYTHONPATH="./" python ./tests/scripts/parsing.py